client/urls.py
from django.urls import path
from .views import *
#из этой же директории импортирую

app_name = 'client'

urlpatterns = [
    path('', index, name = 'index'),
    path('create', create, name = 'create'),
    path('storage', storage, name = 'storage'),
    path('edit<int:client_id>', edit, name = 'edit'),
    path('update<int:client_id>', update, name = 'update'),
    path('delete<int:client_id>', delete, name = 'delete'),
    path('seed', seed, name = 'seed'),
    path('api/show', GetClientInfoView.as_view()),
    path('api/create', GetClientWriteView.as_view()),
    path('api/edit<int:id>', GetClientEditView.as_view()),
    path('api/delete<int:id>', GetClientEditView.as_view()),
]

message/urls.py
from django.urls import path
from .views import *
#из этой же директории импортирую

app_name = 'message'

urlpatterns = [
    path('', index, name = 'index'),
    path('create', create, name = 'create'),
    path('storage', storage, name = 'storage'),
    path('edit', edit, name = 'edit'),
    path('delete', delete, name = 'delete'),
]

notice/urls.py
from django.urls import path
from .views import *
#из этой же директории импортирую
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

app_name = 'notice'
# schema_view = get_schema_view(
#    openapi.Info(
#       title="Snippets API",
#       default_version='v1',
#       description="Test description",
#       terms_of_service="https://probe.fbrq.cloud/v1",
#       contact=openapi.Contact(email="contact@snippets.local"),
#       license=openapi.License(name="BSD License"),
#    ),
#    public=True,
#    permission_classes=[permissions.AllowAny],
# )
urlpatterns = [
    path('', index, name = 'index'),
    path('create', create, name = 'create'),
    path('storage', storage, name = 'storage'),
    path('edit<int:notice_id>', edit, name = 'edit'),
    path('update<int:notice_id>', update, name = 'update'),
    path('delete<int:notice_id>', delete, name = 'delete'),
    path('api/show', GetNoticeInfoView.as_view()),
    path('api/create', GetNoticeWriteInfoView.as_view()),
    path('api/edit<int:id>', GetNoticeEditInfoView.as_view()),
    path('api/delete<int:id>', GetNoticeEditInfoView.as_view()),
    path('api/view<int:id>', GetNoticeViewInfoView.as_view()),
    # path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    # path('api/delete<int:id>', GetNoticeUpdateView.as_view()),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('notice/', include('notice.urls')),
    path('client/', include('client.urls')),
    path('message/', include('message.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/layouts/header.html
{% load static %}
    <!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" data-enable-remember="true" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="../../index3.html" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" class="nav-link">Contact</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

</nav>

templates/layouts/layout.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Blank Page</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/css/admin.css' %}">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

    {% include 'layouts/header.html' %}
    {% include 'layouts/wrapper_left.html' %}
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        {% block content %}{% endblock content %}
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="float-right d-none d-sm-block">
            <b>Version</b> 3.0.5
        </div>
        <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong> All rights
        reserved.
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<script src="{% static '/js/admin.js' %}"></script>



</body>
</html>

templates/layouts/wrapper_left.html
{% load static %}
    <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{% static '/img/user2-160x160.jpg' %}" class="img-circle elevation-2"
                         alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">Echis Begzi</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <li class="nav-item">
                        <a href="{% url 'main' %}" class="nav-link">
                            <i class="nav-icon fas fa-home"></i>
                            <p>Главная</p>
                        </a>
                    </li>

                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-archive"></i>
                            <p>
                                Рассылки
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'notice:index' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Список рассылок</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'notice:create' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Создать рассылку</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-tags"></i>
                            <p>
                                Клиенты
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'client:index' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Список клиенты</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'client:create' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Добавить клиента</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-edit"></i>
                            <p>
                                Сообщения
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{% url 'message:index' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Список сообщений</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>