notice/urls.py
from django.urls import path
from .views import *
#из этой же директории импортирую
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

app_name = 'notice'
# schema_view = get_schema_view(
#    openapi.Info(
#       title="Snippets API",
#       default_version='v1',
#       description="Test description",
#       terms_of_service="https://probe.fbrq.cloud/v1",
#       contact=openapi.Contact(email="contact@snippets.local"),
#       license=openapi.License(name="BSD License"),
#    ),
#    public=True,
#    permission_classes=[permissions.AllowAny],
# )
urlpatterns = [
    path('', index, name = 'index'),
    path('create', create, name = 'create'),
    path('storage', storage, name = 'storage'),
    path('edit<int:notice_id>', edit, name = 'edit'),
    path('update<int:notice_id>', update, name = 'update'),
    path('delete<int:notice_id>', delete, name = 'delete'),
    path('api/show', GetNoticeInfoView.as_view()),
    path('api/create', GetNoticeWriteInfoView.as_view()),
    path('api/edit<int:id>', GetNoticeEditInfoView.as_view()),
    path('api/delete<int:id>', GetNoticeEditInfoView.as_view()),
    path('api/view<int:id>', GetNoticeViewInfoView.as_view()),
    # path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    # path('api/delete<int:id>', GetNoticeUpdateView.as_view()),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('notice/', include('notice.urls')),
    path('client/', include('client.urls')),
    path('message/', include('message.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/models.py
# from django.db import models
#
# # Create your models here.
#
# class Filter(models.Model):
#     code = models.CharField(verbose_name='Код мобильного оператора', max_length=5, null=True)
#     tag = models.CharField(verbose_name='Тэг', max_length=100, null=True)
#
#     def __str__(self):
#         if self.code:
#             return self.code
#         else:
#             return  self.tag
#
#     class Meta:
#         verbose_name = 'Фильтр'
#         verbose_name_plural = 'Фильтры'
#
# class Notice(models.Model):
#     created = models.DateTimeField(verbose_name='Дата и время начала рассылки', auto_now_add=True)
#     text = models.TextField(verbose_name='Текст сообщения')
#
#     ended = models.DateTimeField(verbose_name='Дата и время окончания рассылки')
#     filters = models.ManyToManyField(Filter)
#     def __str__(self):
#         return str(self.created)
#
#     class Meta:
#         verbose_name = 'Рассылка'
#         verbose_name_plural = 'Рассылки'









from django.db import models

# Create your models here.

class Filter(models.Model):
    code = models.CharField(verbose_name='Код мобильного оператора', max_length=5, null=True)
    tag = models.CharField(verbose_name='Тэг', max_length=15, null=True)

    def __str__(self):
        if self.code:
            return self.code
        else:
            return  self.tag

    class Meta:
        verbose_name = 'Фильтр'
        verbose_name_plural = 'Фильтры'

class Notice(models.Model):
    created = models.DateField(verbose_name='Дата создания рассылки', auto_now_add=True)
    text = models.TextField(verbose_name='Текст сообщения')

    started = models.DateField(verbose_name='Дата отправки рассылки')
    ended = models.DateField(verbose_name='Дата окончания рассылки')

    def __str__(self):
        return str(self.created)

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

class Notice_Filter(models.Model):
	notice = models.ForeignKey(Notice, on_delete=models.CASCADE, related_name='filter_table')
	filter = models.ForeignKey(Filter, on_delete=models.SET_NULL, null = True, related_name='notice_table')

	@classmethod
	def create(cls,notice, filter):
		notice_filter = cls(notice=notice,filter=filter)
		return notice_filter

notice/forms.py
from .models import Filter

import datetime


def is_valid(started, ended, text, filters):
    if filters is None:
        filters = []
    context = {'error': False}
    messages = []
    if started == '' or started == None:
        messages.append("Не была выбрана дата начала рассылки")
        context['error'] = True
    if ended == '' or ended == None:
        messages.append("Не была выбрана дата окончания")
        context['error'] = True
    else:
        try:
            ended = datetime.datetime.strptime(ended, "%Y-%m-%d").date()
            started = datetime.datetime.strptime(started, "%Y-%m-%d").date()
        except:
            messages.append("Формат данных начала и конца рассылки не подлежит конвертации в date")
            context['error'] = True
            ended = datetime.date.today()
            started = datetime.date.today()
        if (ended <= datetime.date.today()):
            messages.append("Дата окончания рассылки должен быть позже сегоднешнего числа")
            context['error'] = True
        if (ended <= started):
            messages.append("Дата окончания рассылки должен быть позже даты начала рассылки")
            context['error'] = True
    if (len(text) < 20):
        messages.append(
            "Количество символов в тексте письма должно быть больше 20 на данный момент: " + str(len(self.text)))
        context['error'] = True
    if (len(filters) == 0):
        messages.append("Должны быть выбраны фильтры для рассылки")
        context['error'] = True
    else:
        for filter in filters:
            if Filter.objects.filter(id=filter).get():
                pass
            else:
                messages.append("Выбранный фильтр не был найден, обновите страницу и создайте снова")
                context['error'] = True
                break

    context['messages'] = messages

    return context

notice/views.py
import json
from django.shortcuts import render, redirect, HttpResponse
from rest_framework.response import Response
from rest_framework.views import APIView

from client.models import Client
from .models import Filter, Notice, Notice_Filter
from message.models import Message
from .forms import *
from django.core.paginator import Paginator
from datetime import date, datetime
from django.contrib import messages
from main.views import *
from .serializers import *
from rest_framework import status
from rest_framework.renderers import TemplateHTMLRenderer

@check_notice_for_send_message_decorator
def index(request):

    notices = Notice.objects.select_related().all()
    return render(request, 'notices/index.html', {'notices' : notices})

@check_notice_for_send_message_decorator
def create(request):
    context={}
    filters = Filter.objects.all()
    context['filters'] = filters
    return render(request, 'notices/create.html', context)

def storage(request):
    context = is_valid(request.POST['started'],request.POST['ended'], request.POST['text'], request.POST.getlist('filters'))
    if context['error'] == False:
        notice = Notice()
        notice.ended = datetime.strptime(request.POST['ended'], '%Y-%m-%d').date()
        notice.text = request.POST['text']
        notice.started = datetime.strptime(request.POST['started'], '%Y-%m-%d').date()
        notice.save()

        for filter in request.POST.getlist('filters'):
            notice_filter = Notice_Filter()
            notice_filter.filter_id = filter
            notice_filter.notice_id = notice.id
            notice_filter.save()

        create_messages(notice)
        return redirect('notice:index')

    for message in context['messages']:
        messages.add_message(request, messages.INFO, message)
    return redirect('notice:create')

def edit(request, notice_id):
    context={}
    notice = Notice.objects.get(id = notice_id)
    filters = Filter.objects.all()
    context['filters'] = filters
    notice.ended = str((notice.ended).strftime('%Y-%m-%d'))
    notice.started = str((notice.started).strftime('%Y-%m-%d'))
    context['notice'] = notice
    return render(request, 'notices/edit.html', context)

def update(request, notice_id):
    context = is_valid(request.POST['started'], request.POST['ended'], request.POST['text'],
                       request.POST.getlist('filters'))

    if context['error'] == False:
        notice = Notice.objects.get(id = notice_id)
        notice.ended = request.POST['ended']
        notice.started = request.POST['started']
        notice.text = request.POST['text']
        notice.save()

        filters_table = notice.filter_table.all()
        filters = []
        for filter_table in filters_table:
            filters.append(filter_table.filter.id)


        for filter in request.POST.getlist('filters'):
            if int(filter) in filters:
                filters.remove(int(filter))
            else:
                notice_filter = Notice_Filter()
                notice_filter.filter_id = int(filter)
                notice_filter.notice_id = notice.id
                notice_filter.save()

        if len(filters) != 0:
            for bad_filter in filters:
                Notice_Filter.objects.filter(filter_id = bad_filter).delete()


        return redirect('notice:index')

    for message in context['messages']:
        messages.add_message(request, messages.INFO, message)
    return redirect('notice:edit' + notice_id)

def delete(request, notice_id):
    Notice.objects.filter(id = notice_id).delete()
    return redirect('notice:index')



class GetNoticeInfoView(APIView):
    serializer_class = NoticeWriteSerializer
    model = Notice

    def get(self, request):
        queryset = self.model.objects.all()
        serializer_for_queryset = self.serializer_class(
            instance=queryset,
            many=True
        )
        return Response(serializer_for_queryset.data)

class GetNoticeWriteInfoView(APIView):
    serializer_class = NoticeWriteSerializer
    model = Notice

    def get(self, request):
        context={}
        filters = Filter.objects.all()
        context['filters'] = filters
        return Response(context)

    def post(self, request):
        context = is_valid(request.POST['started'], request.POST['ended'], request.POST['text'],
                           request.POST.getlist('filters'))

        if context['error']:
            return Response(context)
        else:
            serializer_for_writing = self.serializer_class(data=request.data)
            serializer_for_writing.create(request.POST['started'],request.POST['ended'],request.POST['text'], request.POST.getlist('filters'))
        return Response(context)


class GetNoticeEditInfoView(APIView):
    serializer_class = NoticeEditSerializer
    model = Notice

    def get(self, request, id):
        queryset = self.model.objects.all()
        serializer_for_queryset = self.serializer_class(
            instance=queryset,
            many=True
        )
        return Response(serializer_for_queryset.data)

    def put(self, request, id):
        try:
            instance = Notice.objects.get(id=id)
        except:
            return Response({"error": "Такого Notice не существует"})

        serializer_for_updating = self.serializer_class(data=request.data, instance=instance)
        serializer_for_updating.is_valid(raise_exception=True)
        serializer_for_updating.save()
        return Response(
            data=serializer_for_updating.data,
            status=status.HTTP_202_ACCEPTED
        )

    def delete(self, request, id):

        try:
            instance = Notice.objects.get(id=id)
        except:
            return Response({"error": "Такого Notice не существует"})

        instance.delete()

        return Response({'messages': ['Успешное удаление']})



class GetNoticeViewInfoView(APIView):
    serializer_class = NoticeViewSerializer
    model = Notice
    def get(self, request, id):
        queryset = self.model.objects.filter(id=id).all()
        serializer_for_queryset = self.serializer_class(
            instance=queryset,
            many=True
        )
        return Response(serializer_for_queryset.data)

templates/notices/create.html
{% extends 'layouts/layout.html' %}
{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Создание рассылки</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main' %}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'notice:index' %}">Рассылки</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        {% if  messages  %}
                            <div class="alert alert-danger">
                                {% for message in  messages  %}
                                    <ul class="list-unstyled">
                                        {{ message }}
                                    </ul>
                                {% endfor %}
                            </div>

                        {% endif %}
                        <div class="card-header">
                            <h3 class="card-title">Новая рассылка</h3>
                        </div>
                        <!-- /.card-header -->

                        <form role="form" method="post" action="{% url 'notice:storage' %}">
                            {% csrf_token %}
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="content">Дата начала рассылки: </label>
                                    <input name='started' type="date" required>
                                </div>

                                <div class="form-group">
                                    <label for="content">Дата окончания рассылки: </label>
                                    <input name='ended' type="date" required>
                                </div>

                                <div class="form-group">
                                    <label for="content">Текст сообщения</label>
                                    <textarea name="text" class="form-control" id="content" rows="7"
                                              placeholder="Текст сообщения ..." required></textarea>
                                </div>

                                <div class="form-group">
                                    <label for="filters">Фильтры</label>
                                    <select name="filters" id="filters" class="select2" multiple="multiple"
                                            data-placeholder="Выбор фильтров" style="width: 100%;" required>
                                        {% for filter in filters %}
                                            {% if filter.code == None %}
                                                <option value="{{ filter.id }}">{{ filter.tag }}</option>
                                            {% else %}
                                                <option value="{{ filter.id }}">{{ filter.code }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Создать</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock content %}

templates/notices/edit.html
{% extends 'layouts/layout.html' %}
{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Редактирование рассылки</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main' %}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'notice:index' %}">Рассылки</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        {% if  messages  %}
                            <div class="alert alert-danger">
                                {% for message in  messages  %}
                                    <ul class="list-unstyled">
                                        {{ message }}
                                    </ul>
                                {% endfor %}
                            </div>

                        {% endif %}
                        <div class="card-header">
                            <h3 class="card-title">Новая рассылка</h3>
                        </div>
                        <!-- /.card-header -->

                        <form role="form" method="post" action="{% url 'notice:update' notice.id %}">
                            {% csrf_token %}
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="content">Дата начала рассылки: </label>
                                    <input name='started' type="date" required value="{{ notice.started }}">
                                </div>

                                <div class="form-group">
                                    <label for="content">Дата окончания рассылки: </label>
                                    <input name='ended' type="date" required value="{{ notice.ended }}">
                                </div>

                                <div class="form-group">
                                    <label for="content">Текст сообщения</label>
                                    <textarea name="text" class="form-control" id="content" rows="7"
                                              placeholder="Текст сообщения ..." required>{{ notice.text }}</textarea>
                                </div>

                                <div class="form-group">
                                    <label for="filters">Фильтры</label>
                                    <select name="filters" id="filters" class="select2" multiple="multiple"
                                            data-placeholder="Выбор фильтров" style="width: 100%;" required>
                                                {% for filter in filters %}
                                                    {% if filter.code == None %}
                                                        <option value="{{ filter.id }}"
                                                            {% for filter_check in notice.filter_table.all %}
                                                                {% if filter.id == filter_check.filter.id %}
                                                                    selected
                                                                {% endif %}
                                                            {% endfor %}
                                                        >{{ filter.tag }}</option>
                                                    {% else %}
                                                        <option value="{{ filter.id }}"
                                                            {% for filter_check in notice.filter_table.all %}
                                                                {% if filter.id == filter_check.filter.id %}
                                                                    selected
                                                                {% endif %}
                                                            {% endfor %}
                                                        >{{ filter.code }}</option>
                                                    {% endif %}
                                                {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock content %}

templates/notices/index.html
{% extends 'layouts/layout.html' %}
{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Рассылки</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main' %}">Home</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Список рассылок</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <a href="{% url 'notice:create' %}" class="btn btn-primary mb-3">Создать расслку</a>
                            {% if notices %}
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover text-nowrap">
                                        <thead>
                                        <tr>
                                            <th style="width: 30px">#</th>
                                            <th>Дата начала</th>
                                            <th>Дата окончания</th>
                                            <th>Фильтры</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for notice in notices %}
                                            <tr>
                                                <td>{{ notice.id }}</td>
                                                <td>{{ notice.started }}</td>
                                                <td>{{ notice.ended }}</td>
                                                <td> {% if notice.filter_table.all.count == 0  %}
                                                        Нет Фильтров
                                                    {% else %}
                                                        {{ notice.filter_table.all.count}}
                                                        Фильтрa есть
                                                    {% endif%}

                                                </td>
                                                <td>
                                                    <a href="{% url 'notice:edit' notice.id %}"
                                                       class="btn btn-info btn-sm float-left mr-1">
                                                        <i class="fas fa-pencil-alt"></i>
                                                    </a>

                                                    <form
                                                        action="{% url 'notice:delete' notice.id %}"
                                                        method="post" class="float-left">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-danger btn-sm"
                                                                onclick="return confirm('Подтвердите удаление')">
                                                            <i
                                                                class="fas fa-trash-alt"></i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            {% else %}
                                <p>Рассылок пока нет...</p>
                            {% endif %}
                        </div>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock content %}