client/urls.py
from django.urls import path
from .views import *
#из этой же директории импортирую

app_name = 'client'

urlpatterns = [
    path('', index, name = 'index'),
    path('create', create, name = 'create'),
    path('storage', storage, name = 'storage'),
    path('edit<int:client_id>', edit, name = 'edit'),
    path('update<int:client_id>', update, name = 'update'),
    path('delete<int:client_id>', delete, name = 'delete'),
    path('seed', seed, name = 'seed'),
    path('api/show', GetClientInfoView.as_view()),
    path('api/create', GetClientWriteView.as_view()),
    path('api/edit<int:id>', GetClientEditView.as_view()),
    path('api/delete<int:id>', GetClientEditView.as_view()),
]

web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('notice/', include('notice.urls')),
    path('client/', include('client.urls')),
    path('message/', include('message.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models

# Create your models here.

class TimeZone(models.Model):
    code = models.CharField(verbose_name='Часовой пояс', max_length= 10)
    tag = models.CharField(verbose_name='Обозначение', max_length= 5)
    title = models.CharField(verbose_name='Наименование', max_length= 30)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Часовой пояс'
        verbose_name_plural = 'Часовой пояса'

class Client(models.Model):
    phone = models.CharField(verbose_name='Номер телефона', max_length=12, unique=True)
    code = models.CharField(verbose_name='Код мобильного оператора', max_length=5)
    tag = models.CharField(verbose_name='Тэг', max_length=15)

    time_zone = models.ForeignKey(TimeZone, on_delete= models.SET_NULL, null = True, related_name='clients')

    def __str__(self):
        return self.phone

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

client/forms.py
from .models import TimeZone

class ClientValid:
    def __init__(self, phone, code, tag, time_zone_id):
        self.phone = phone
        self.code = code
        self.tag = tag
        self.time_zone_id = time_zone_id

    def is_valid(self):
        context = {'error' : False }
        messages = []
        if self.phone == '' or self.phone == None:
            messages.append("Не ввели номер телефона")
            context['error'] = True
        else:
            if (len(self.phone) != 12):
                messages.append("Номер телефона должен быть равен 12 символов")

        if self.code == '' or self.code == None:
            messages.append("Не ввели Код мобильного оператора")
            context['error'] = True
        else:
            if (len(self.code) > 5):
                messages.append("Код мобильного оператора не должен быть больше 5 символов")

        if self.tag == '' or self.tag == None:
            messages.append("Не ввели тег")
            context['error'] = True
        else:
            if (len(self.tag) > 12):
                messages.append("Тег не должен быть больше 15 символов")
                context['error'] = True

        if TimeZone.objects.filter(id = self.time_zone_id).get():
            pass
        else:
            messages.append("Выбранный часовой пояс не был найден, обновите страницу и попытайтесь заного")
            context['error'] = True


        context['messages'] = messages

        return context

client/views.py
from django_seed import Seed
import json
from django.shortcuts import render, redirect, HttpResponse
from rest_framework import status

from .models import TimeZone, Client
from .forms import ClientValid
from notice.models import Filter
from django.contrib import messages
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializers import ClientSerializer, ClientWriteSerializer
from main.views import *

@check_notice_for_send_message_decorator
def index(request):
    clients = Client.objects.all()
    return render(request, 'clients/index.html', {'clients' : clients})

@check_notice_for_send_message_decorator
def create(request):
    context={}
    timezone = TimeZone.objects.all()
    context['timezone'] = timezone
    return render(request, 'clients/create.html', context)

def help_storage(code, tag):
    if code != None or code != '':
        if Filter.objects.filter(code=code):
            pass
        else:
            filter = Filter()
            filter.code = code
            filter.save()
    if tag != None or tag != '':
        if Filter.objects.filter(code=tag):
            pass
        else:
            filter = Filter()
            filter.tag = tag
            filter.save()

def storage(request):
    client_valid = ClientValid(request.POST['phone'],request.POST['code'], request.POST['tag'], request.POST['time_zone_id'])
    context = client_valid.is_valid()
    if context['error'] == False:
        client = Client()
        client.phone = request.POST['phone']
        client.code = request.POST['code']
        client.tag = request.POST['tag']
        client.time_zone_id = request.POST['time_zone_id']
        client.save()

        help_storage(client.code, client.tag)

        return redirect('client:index')
    for message in context['messages']:
        messages.add_message(request, messages.INFO, message)
    return redirect('client:create')

def edit(request, client_id):
    context={}
    timezone = TimeZone.objects.all()
    client = Client.objects.get(id = client_id)
    context['timezone'] = timezone
    context['client'] = client
    return render(request, 'clients/edit.html', context)

def update(request, client_id):
    client_valid = ClientValid(request.POST['phone'], request.POST['code'], request.POST['tag'],
                               request.POST['time_zone_id'])
    context = client_valid.is_valid()
    if context['error'] == False:
        client = Client.objects.get(id = client_id)

        if (client.code != request.POST['code']):
            if Filter.objects.filter(code = client.code) and len(Client.objects.filter(code = client.code).all()) == 1:
                Filter.objects.filter(code=client.code).delete()
        if (client.tag != request.POST['tag']):
            if Filter.objects.filter(tag = client.tag) and len(Client.objects.filter(tag = client.tag).all()) == 1:
                Filter.objects.filter(tag=client.tag).delete()

        client.phone = request.POST['phone']
        client.code = request.POST['code']
        client.tag = request.POST['tag']
        client.time_zone_id = request.POST['time_zone_id']
        client.save()

        help_storage(client.code, client.tag)

        return redirect('client:index')
    for message in context['messages']:
        messages.add_message(request, messages.INFO, message)
    return redirect('client:edit' + str(client_id))

def delete(request, client_id):
    client = Client.objects.get(id = client_id)
    if Filter.objects.filter(code = client.code) and len(Client.objects.filter(code = client.code).all()) == 1:
        Filter.objects.filter(code=client.code).delete()
    if Filter.objects.filter(tag = client.tag) and len(Client.objects.filter(tag = client.tag).all()) == 1:
        Filter.objects.filter(tag=client.tag).delete()
    client.delete()
    return redirect('client:index')

def seed(request):
    seeder = Seed.seeder()
    seeder.add_entity(Client, 10)

    seeder.execute()

    clients = Client.objects.all()
    for client in clients:
        help_storage(client.code, client.tag)
    return HttpResponse(123)


class GetClientInfoView(APIView):

    def get(self, request):
        # Извлекаем набор всех записей из таблицы Capital
        queryset = Client.objects.all()
        # Создаём сериалайзер для извлечённого наборa записей
        serializer_for_queryset = ClientSerializer(
            instance=queryset,  # Передаём набор записей
            many=True  # На вход подается именно набор, а не одна запись
        )
        return Response(serializer_for_queryset.data)

class GetClientWriteView(APIView):
    serializer_class = ClientWriteSerializer
    model = Client

    def get(self, request):
        # Извлекаем набор всех записей из таблицы Writer
        # Создаём сериалайзер для извлечённого наборa записей
        serializer_for_reading = self.serializer_class(
            instance=self.model.objects.all(),  # Передаём набор записей
            many=True  # На вход подается именно набор, а не одна запись
        )
        return Response(serializer_for_reading.data)

    def post(self, request):
        serializer_for_writing = self.serializer_class(data=request.data)
        serializer_for_writing.is_valid(raise_exception=True)
        serializer_for_writing.save()
        return Response(
            data=serializer_for_writing.data,
            status=status.HTTP_201_CREATED
        )

class GetClientEditView(APIView):
    serializer_class = ClientWriteSerializer
    model = Client

    def get(self, request, id):
        # Извлекаем набор всех записей из таблицы Writer
        # Создаём сериалайзер для извлечённого наборa записей
        serializer_for_reading = self.serializer_class(
            instance=self.model.objects.filter(id=id),  # Передаём набор записей
            many=True  # На вход подается именно набор, а не одна запись
        )
        return Response(serializer_for_reading.data)
    def put(self, request, id):

        try:
            instance = Client.objects.get(id=id)
        except:
            return Response({"error": "Такого Client не существует"})

        serializer_for_updating = self.serializer_class(data=request.data, instance=instance)
        serializer_for_updating.is_valid(raise_exception=True)
        serializer_for_updating.save()
        return Response(
            data=serializer_for_updating.data,
            status=status.HTTP_202_ACCEPTED
        )

    def delete(self, request, id):

        try:
            instance = Client.objects.get(id=id)
        except:
            return Response({"error": "Такого Client не существует"})


        if Filter.objects.filter(code = instance.code) and len(Client.objects.filter(code = instance.code).all()) == 1:
            Filter.objects.filter(code=instance.code).delete()
        if Filter.objects.filter(tag = instance.tag) and len(Client.objects.filter(tag = instance.tag).all()) == 1:
            Filter.objects.filter(tag=instance.tag).delete()
        instance.delete()

        return Response(
            status=status.HTTP_200_OK
        )

templates/clients/create.html
{% extends 'layouts/layout.html' %}
{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Добавение клиента</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main' %}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'client:index' %}">Клиенты</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        {% if  messages  %}
                            <div class="alert alert-danger">
                                {% for message in  messages  %}
                                    <ul class="list-unstyled">
                                        {{ message }}
                                    </ul>
                                {% endfor %}
                            </div>

                        {% endif %}
                        <div class="card-header">
                            <h3 class="card-title">Новый клиент</h3>
                        </div>
                        <!-- /.card-header -->

                        <form role="form" method="post" action="{% url 'client:storage' %}">
                            {% csrf_token %}
                            <div class="card-body">

                                <div class="form-group">
                                    <label for="phone">Номер телефона: </label>
                                    <input name='phone' type="text" >
                                </div>

                                <div class="form-group">
                                    <label for="code">Код мобильного оператора: </label>
                                    <input name='code' type="text" >
                                </div>

                                <div class="form-group">
                                    <label for="tag">Тег: </label>
                                    <input name='tag' type="text" >
                                </div>

                                <div class="form-group">
                                    <label for="time_zone_id">Часовой пояс</label>
                                    <select class="form-control" id="time_zone_id" name="time_zone_id">
                                        {% for tz in timezone %}
                                            <option value="{{ tz.id }}">{{ tz.title }}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Добавить</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock content %}

templates/clients/edit.html
{% extends 'layouts/layout.html' %}
{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Редактирование клиента</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main' %}">Home</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'client:index' %}">Клиенты</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        {% if  messages  %}
                            <div class="alert alert-danger">
                                {% for message in  messages  %}
                                    <ul class="list-unstyled">
                                        {{ message }}
                                    </ul>
                                {% endfor %}
                            </div>

                        {% endif %}
                        <div class="card-header">
                            <h3 class="card-title">Новый клиент</h3>
                        </div>
                        <!-- /.card-header -->

                        <form role="form" method="post" action="{% url 'client:update' client.id %}">
                            {% csrf_token %}
                            <div class="card-body">

                                <div class="form-group">
                                    <label for="phone">Номер телефона: </label>
                                    <input name='phone' type="text" value="{{client.phone}}">
                                </div>

                                <div class="form-group">
                                    <label for="code">Код мобильного оператора: </label>
                                    <input name='code' type="text" value="{{ client.code }}">
                                </div>

                                <div class="form-group">
                                    <label for="tag">Тег: </label>
                                    <input name='tag' type="text" value="{{ client.tag }}">
                                </div>

                                <div class="form-group">
                                    <label for="time_zone_id">Часовой пояс</label>
                                    <select class="form-control" id="time_zone_id" name="time_zone_id">
                                        {% for tz in timezone %}
                                            <option value="{{ tz.id }}"
                                                {% if tz.id == client.time_zone.id %}
                                                    selected
                                                {% endif %}
                                            >{{ tz.title }}</option>
                                        {% endfor %}
                                    </select>
                                </div>

                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>

                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock content %}

templates/clients/index.html
{% extends 'layouts/layout.html' %}
{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Клиенты</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'main' %}">Home</a></li>
                        <li class="breadcrumb-item active">Blank Page</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Клиенты</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <a href="{% url 'client:create' %}" class="btn btn-primary mb-3">Добавить клиента</a>
                            {% if clients %}
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover text-nowrap">
                                        <thead>
                                        <tr>
                                            <th style="width: 30px">#</th>
                                            <th>Номер телефона</th>
                                            <th>Код мобильного оператора</th>
                                            <th>Тег</th>
                                            <th>Часовой пояс</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for client in clients %}
                                            <tr>
                                                <td>{{ client.id }}</td>
                                                <td>{{ client.phone }}</td>
                                                <td>{{ client.code }}</td>
                                                <td>{{ client.tag }}</td>
                                                <td>{{ client.time_zone.code }}</td>
                                                <td>
                                                    <a href="{% url 'client:edit' client.id %}"
                                                       class="btn btn-info btn-sm float-left mr-1">
                                                        <i class="fas fa-pencil-alt"></i>
                                                    </a>

                                                    <form
                                                        action="{% url 'client:delete' client.id %}"
                                                        method="post" class="float-left">
                                                        {% csrf_token %}
                                                        <button type="submit" class="btn btn-danger btn-sm"
                                                                onclick="return confirm('Подтвердите удаление')">
                                                            <i
                                                                class="fas fa-trash-alt"></i>
                                                        </button>
                                                    </form>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            {% else %}
                                <p>Клиентов пока нет...</p>
                            {% endif %}
                        </div>
                    </div>
                    <!-- /.card -->

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock content %}